/* ══════════════════════════════════════════════════
   MOCK EXAM  (30 questions)
══════════════════════════════════════════════════ */
const EXAM = [
{q:"Choose the correct form: Mijn kat ___ op de kast gesprongen.",opts:["is","zijn","heeft","heb"],ans:enc("is"),topic:"Perfectum hebben/zijn"},
{q:"'Jullie ___ uit Argentinië?' Choose the correct verb form.",opts:["kom","komt","komen","gekomen"],ans:enc("komen"),topic:"Verb conjugation"},
{q:"How do you say 11:45 in Dutch?",opts:["kwart over elf","kwart voor elf","kwart voor twaalf","vijftien voor twaalf"],ans:enc("kwart voor twaalf"),topic:"De klok"},
{q:"'Ik wil dat een heel goed/___ idee.'",opts:["goed","goede","goeds","goeie"],ans:enc("goed"),topic:"Adjectives"},
{q:"Form the perfectum of 'betalen':",opts:["gebetaald","betaald","gebetalen","betalen"],ans:enc("betaald"),topic:"Perfectum formation"},
{q:"Choose the possessive: 'Dat is Mariska en ___ achternaam is Jansen.'",opts:["zijn","haar","hun","uw"],ans:enc("haar"),topic:"Possessive pronouns"},
{q:"Which article goes with 'meisje'?",opts:["de","het","een (only)","no article"],ans:enc("het"),topic:"De/Het words"},
{q:"'Ik ___ naar school.' Choose the correct modal verb.",opts:["kan","mag","moet","wil"],ans:enc("moet"),topic:"Modal verbs"},
{q:"What is the plural of 'taxi'?",opts:["taxien","taxis","taxi's","taxees"],ans:enc("taxi's"),topic:"Plural forms"},
{q:"'Deze jas is ___ dan die jas.'",opts:["duurer","duurder","meer duur","duurste"],ans:enc("duurder"),topic:"Comparative"},
{q:"Fill in: 'Zullen we naar de bioscoop gaan? Ja, ___ is een goed idee!'",opts:["die","dit","dat","deze"],ans:enc("dat"),topic:"Die/dat reference"},
{q:"'Wij spreken geen Nederlands. Wie kan ___ helpen?'",opts:["ze","ons","hen","hun"],ans:enc("ons"),topic:"Personal pronouns"},
{q:"Which is a HARD conjunction?",opts:["en","maar","want","omdat"],ans:enc("omdat"),topic:"Conjunctions"},
{q:"'De cursus begint ___ 10 uur.'",opts:["in","op","om","aan"],ans:enc("om"),topic:"Prepositions in/om/op"},
{q:"'Gisteren ___ mijn vriend gewerkt.'",opts:["is","zijn","heeft","heb"],ans:enc("heeft"),topic:"Perfectum hebben/zijn"},
{q:"'Maandag ___ naar Amsterdam.'",opts:["we gaan","gaan we","ga we","gaan"],ans:enc("gaan we"),topic:"Inversion"},
{q:"'Ik ___ samen met vrienden gedanst.'",opts:["ben","zijn","heb","heeft"],ans:enc("heb"),topic:"Perfectum hebben/zijn"},
{q:"How do you say 11:30 in Dutch?",opts:["half elf","half twaalf","dertig over elf","kwart voor twaalf"],ans:enc("half twaalf"),topic:"De klok"},
{q:"What does 'Waar kom je vandaan?' mean?",opts:["Where do you live?","Where are you going?","Where do you come from?","Where do you work?"],ans:enc("Where do you come from?"),topic:"Useful phrases"},
{q:"'luisteren' — imperfectum, ik-form:",opts:["luisterte","luisterde","geluisterd","luisterden"],ans:enc("luisterde"),topic:"Imperfectum"},
{q:"'Als kind ___ ik piloot worden.'",opts:["wil","wou","wilde","wilden"],ans:enc("wilde"),topic:"Modal verbs past"},
{q:"'Ik ___ vroeger niet naar buiten.'",opts:["mochten","moch","mocht","mochtte"],ans:enc("mocht"),topic:"Modal verbs past"},
{q:"Present tense of separable verb 'aankomen' for 'ik':",opts:["Ik aankomen.","Ik kom aan.","Ik aankom.","Ik ben aangekomen."],ans:enc("Ik kom aan."),topic:"Separable verbs"},
{q:"Perfectum of 'aankomen' in a sentence:",opts:["Ik heb aangekomen.","Ik ben aankgekomen.","Ik ben aangekomen.","Ik heb aankomen."],ans:enc("Ik ben aangekomen."),topic:"Separable verbs"},
{q:"'Wat ___ p.p.?'",opts:["bedoel","bedoelt","betekent","betekenen"],ans:enc("betekent"),topic:"Bedoelen/betekenen"},
{q:"'___ T-shirt is goedkoper.'",opts:["Deze","Die","Dit","Dat"],ans:enc("Dit"),topic:"Demonstrative pronouns"},
{q:"Which word order is correct with 'omdat'?",opts:["Ik kom niet omdat ik ben ziek.","Ik kom niet omdat ik ziek ben.","Ik kom niet omdat ziek ik ben.","Omdat ik ben ziek, ik kom niet."],ans:enc("Ik kom niet omdat ik ziek ben."),topic:"Conjunctions"},
{q:"'___ universiteit' — which article?",opts:["het","de","een (no rule applies)","both de and het"],ans:enc("de"),topic:"De/Het words"},
{q:"'Laura ___ 35 jaar geworden.'",opts:["heeft","heb","is","zijn"],ans:enc("is"),topic:"Perfectum hebben/zijn"},
{q:"'Ik ga de krant vaker lezen ___ ik nieuwe woorden leer.'",opts:["omdat","want","zodat","als"],ans:enc("zodat"),topic:"Conjunctions"},
];
